const en = {
  intro: 'From connecting your number to your first conversation. One step at a time.',
  connect: 'Connect your number', test: 'Make your first test reservation.', testLead: 'Make your first', testAccent: 'test reservation.', preferences: 'Optional settings',
  number: 'Customer-facing number', connected: 'Number registered', pending: 'Verification in progress',
  disconnected: 'Connect to get started', unknown: 'Connection could not be checked',
  retry: 'Check again', support: 'Get help connecting',
  migration: 'Already using this number in WhatsApp? Contact support before changing it. This flow does not transfer existing chats.',
  registeredHint: 'Registration is complete. Test an incoming conversation before sharing the number with customers.',
  testHint: 'Open WhatsApp, ask about opening hours, then try making a reservation. Check that it appears in your dashboard.',
  open: 'Open WhatsApp', reservations: 'Check reservations', copy: 'Copy number', copied: 'Copied', copyFailed: 'Could not copy. Select the number above.',
  locked: 'Register your number first to test the customer experience.',
  delivery: 'Check outbound delivery', deliveryHint: 'Sends one test through the platform sender. Delivery does not verify that your own number receives messages or creates reservations.',
  send: 'Send test message', sending: 'Requesting test…', accepted: 'Request accepted. Waiting for delivery confirmation.',
  recipient: 'Your number to receive the test (with country code)', cooldown: 'Please wait before sending another test to this number.',
  testUnavailable: 'Outbound messaging is not configured. Contact support to enable it.',
  templateUnavailable: 'Could not confirm an approved test template in your restaurant’s language. Contact support. No message was sent.',
  configIncomplete: 'Could not confirm your restaurant’s name and language. Check its settings before testing.',
  deliveryError: 'Could not check delivery. Try again.', details: 'Delivery details',
  noTest: 'No delivery test yet.', lastTest: 'Latest delivery test',
  unconfirmed: 'Delivery not confirmed', unconfirmedHint: 'No delivery receipt was recorded within 10 minutes. This does not prove the message failed. Check again or send a new test.',
  personality: 'How the AI replies', notifications: 'Notifications for you',
  notificationHint: 'Your personal number is separate from the number customers contact.',
  automated: 'Feedback and surveys', saved: 'Saved', save: 'Save notifications',
  enabled: 'Enable WhatsApp notifications', owner: 'Your personal WhatsApp number (with country code)',
  loadError: 'We could not load WhatsApp settings. Nothing has been changed.', refreshing: 'Checking…',
  pageIntro: 'Connect your number. Then check that a real reservation reaches the dashboard.',
  connectionStep: '01 / Customer number', proofStep: '01 / Real test', detailStep: '02 / Fine-tune',
  activeTitle: 'Your number is registered.', pendingTitle: 'Confirm your number.', disconnectedTitle: 'Bring your number to Seatable.',
  errorTitle: 'Connection needs attention.', errorStatus: 'Verification error', activeNext: 'Next: send a real message from another phone and check that the reservation appears in the dashboard.',
  pendingNext: 'Next: enter the code Meta sent to your number. This step does not yet prove inbound bookings.',
  disconnectedNext: 'Next: verify a number you control. Existing chats will not be transferred.',
  errorNext: 'Check the issue below before retrying. No customer message was routed by this screen.',
  registeredOnly: 'Incoming messages and reservations are not yet verified.',
  suggestedLabel: 'Suggested message', suggestedMessage: 'Hi, I would like a table for two. What times do you have available?',
  suggestedHint: 'This opens prefilled in WhatsApp. You decide whether to send it.',
  panelStep: 'Next / in the dashboard', openPanel: 'Open reservations dashboard', settingsTitle: 'WhatsApp settings',
  startStep: 'Start a conversation', startHint: 'Ask about hours, then request a table.',
  confirmStep: 'Check the booking', confirmHint: 'Check the date, time and party size in your dashboard.',
  postVisitPolicy: 'Feedback and surveys are configured separately. Review both before enabling them.',
  verificationCode: 'Verification code',
};
type Copy = typeof en;
const pt: Copy = {
  intro: 'Do seu número conectado à primeira conversa. Um passo de cada vez.',
  connect: 'Conectar seu número', test: 'Faça sua primeira reserva de teste.', testLead: 'Faça sua primeira', testAccent: 'reserva de teste.', preferences: 'Ajustes opcionais',
  number: 'Número que atende clientes', connected: 'Número registrado', pending: 'Verificação em andamento',
  disconnected: 'Conecte para começar', unknown: 'Não foi possível verificar a conexão',
  retry: 'Verificar novamente', support: 'Ajuda para conectar',
  migration: 'Já usa esse número no WhatsApp? Fale com o suporte antes de alterá-lo. Este fluxo não transfere conversas existentes.',
  registeredHint: 'Registro concluído. Teste uma conversa recebida antes de divulgar o número aos clientes.',
  testHint: 'Abra o WhatsApp, pergunte o horário e tente fazer uma reserva. Confira se ela aparece no painel.',
  open: 'Abrir WhatsApp', reservations: 'Conferir reservas', copy: 'Copiar número', copied: 'Copiado', copyFailed: 'Não foi possível copiar. Selecione o número acima.',
  locked: 'Registre seu número primeiro para testar a experiência do cliente.',
  delivery: 'Verificar envio de mensagens', deliveryHint: 'Envia um teste pelo remetente da plataforma. A entrega não comprova que seu próprio número recebe mensagens ou cria reservas.',
  send: 'Enviar mensagem de teste', sending: 'Solicitando teste…', accepted: 'Pedido aceito. Aguardando confirmação de entrega.',
  recipient: 'Seu número para receber o teste (com código do país)', cooldown: 'Aguarde antes de enviar outro teste para este número.',
  testUnavailable: 'O envio de mensagens não está configurado. Fale com o suporte para ativá-lo.',
  templateUnavailable: 'Não foi possível confirmar um modelo de teste aprovado no idioma do restaurante. Fale com o suporte. Nenhuma mensagem foi enviada.',
  configIncomplete: 'Não foi possível confirmar o nome e o idioma do restaurante. Confira os ajustes antes de testar.',
  deliveryError: 'Não foi possível consultar a entrega. Tente novamente.', details: 'Detalhes da entrega',
  noTest: 'Nenhum teste de entrega ainda.', lastTest: 'Último teste de entrega',
  unconfirmed: 'Entrega não confirmada', unconfirmedHint: 'Nenhuma confirmação de entrega foi registrada em 10 minutos. Isso não comprova falha no envio. Verifique novamente ou faça um novo teste.',
  personality: 'Como a IA responde', notifications: 'Notificações para você',
  notificationHint: 'Seu número pessoal é diferente do número que atende clientes.',
  automated: 'Avaliações e pesquisas', saved: 'Salvo', save: 'Salvar notificações',
  enabled: 'Ativar notificações por WhatsApp', owner: 'Seu WhatsApp pessoal (com código do país)',
  loadError: 'Não foi possível carregar os ajustes do WhatsApp. Nada foi alterado.', refreshing: 'Verificando…',
  pageIntro: 'Conecte seu número. Depois, confira se uma reserva real chega ao painel.',
  connectionStep: '01 / Número dos clientes', proofStep: '01 / Teste real', detailStep: '02 / Ajustes finos',
  activeTitle: 'Seu número foi registrado.', pendingTitle: 'Confirme seu número.', disconnectedTitle: 'Traga seu número para a Seatable.',
  errorTitle: 'A conexão precisa de atenção.', errorStatus: 'Erro na verificação', activeNext: 'Próximo passo: envie uma mensagem real de outro telefone e confira se a reserva aparece no painel.',
  pendingNext: 'Próximo passo: digite o código enviado pela Meta. Esta etapa ainda não comprova reservas recebidas.',
  disconnectedNext: 'Próximo passo: verifique um número sob seu controle. Conversas existentes não serão transferidas.',
  errorNext: 'Confira o problema abaixo antes de tentar novamente. Nenhuma mensagem foi roteada por esta tela.',
  registeredOnly: 'Mensagens recebidas e reservas ainda não foram comprovadas.',
  suggestedLabel: 'Mensagem sugerida', suggestedMessage: 'Olá, quero reservar uma mesa para duas pessoas. Quais horários vocês têm?',
  suggestedHint: 'A mensagem abre preenchida no WhatsApp. Você decide se envia.',
  panelStep: 'Depois / no painel', openPanel: 'Abrir painel de reservas', settingsTitle: 'Ajustes do WhatsApp',
  startStep: 'Inicie a conversa', startHint: 'Pergunte o horário e peça uma mesa.',
  confirmStep: 'Confira a reserva', confirmHint: 'Confira data, hora e número de pessoas no painel.',
  postVisitPolicy: 'Feedback e pesquisas são configurados separadamente. Revise os dois fluxos antes de ativá-los.',
  verificationCode: 'Código de verificação',
};
const es: Copy = {
  intro: 'De conectar tu número a la primera conversación. Paso a paso.',
  connect: 'Conectar tu número', test: 'Haz tu primera reserva de prueba.', testLead: 'Haz tu primera', testAccent: 'reserva de prueba.', preferences: 'Ajustes opcionales',
  number: 'Número para clientes', connected: 'Número registrado', pending: 'Verificación en curso',
  disconnected: 'Conecta para empezar', unknown: 'No se pudo comprobar la conexión',
  retry: 'Comprobar de nuevo', support: 'Ayuda para conectar',
  migration: '¿Ya usas este número en WhatsApp? Contacta con soporte antes de cambiarlo. Este proceso no transfiere conversaciones existentes.',
  registeredHint: 'Registro completado. Prueba una conversación entrante antes de compartir el número.',
  testHint: 'Abre WhatsApp, pregunta el horario e intenta hacer una reserva. Comprueba que aparece en el panel.',
  open: 'Abrir WhatsApp', reservations: 'Ver reservas', copy: 'Copiar número', copied: 'Copiado', copyFailed: 'No se pudo copiar. Selecciona el número de arriba.',
  locked: 'Registra tu número primero para probar la experiencia del cliente.',
  delivery: 'Comprobar el envío de mensajes', deliveryHint: 'Envía una prueba desde el remitente de la plataforma. La entrega no confirma que tu propio número reciba mensajes o cree reservas.',
  send: 'Enviar mensaje de prueba', sending: 'Solicitando prueba…', accepted: 'Solicitud aceptada. Esperando confirmación de entrega.',
  recipient: 'Tu número para recibir la prueba (con código de país)', cooldown: 'Espera antes de enviar otra prueba a este número.',
  testUnavailable: 'El envío no está configurado. Contacta con soporte.',
  templateUnavailable: 'No se pudo confirmar una plantilla de prueba aprobada en el idioma del restaurante. Contacta con soporte. No se envió ningún mensaje.',
  configIncomplete: 'No se pudo confirmar el nombre y el idioma del restaurante. Revisa los ajustes antes de probar.',
  deliveryError: 'No se pudo consultar la entrega.', details: 'Detalles de entrega',
  noTest: 'Todavía no hay pruebas.', lastTest: 'Última prueba de entrega',
  unconfirmed: 'Entrega no confirmada', unconfirmedHint: 'No se registró confirmación de entrega en 10 minutos. Esto no demuestra un fallo de envío. Comprueba de nuevo o envía otra prueba.',
  personality: 'Cómo responde la IA', notifications: 'Notificaciones para ti',
  notificationHint: 'Tu número personal es distinto del número que atiende a clientes.',
  automated: 'Opiniones y encuestas', saved: 'Guardado', save: 'Guardar notificaciones',
  enabled: 'Activar notificaciones por WhatsApp', owner: 'Tu WhatsApp personal (con código de país)',
  loadError: 'No se pudieron cargar los ajustes. No se cambió nada.', refreshing: 'Comprobando…',
  pageIntro: 'Conecta tu número. Después, comprueba que una reserva real llegue al panel.',
  connectionStep: '01 / Número de clientes', proofStep: '01 / Prueba real', detailStep: '02 / Ajustes',
  activeTitle: 'Tu número está registrado.', pendingTitle: 'Confirma tu número.', disconnectedTitle: 'Trae tu número a Seatable.',
  errorTitle: 'La conexión necesita atención.', errorStatus: 'Error de verificación', activeNext: 'Siguiente paso: envía un mensaje real desde otro teléfono y comprueba que la reserva aparece en el panel.',
  pendingNext: 'Siguiente paso: introduce el código enviado por Meta. Este paso aún no demuestra reservas entrantes.',
  disconnectedNext: 'Siguiente paso: verifica un número que controles. No se transferirán los chats existentes.',
  errorNext: 'Revisa el problema antes de volver a intentarlo. Esta pantalla no ha dirigido ningún mensaje.',
  registeredOnly: 'Los mensajes entrantes y las reservas aún no están comprobados.',
  suggestedLabel: 'Mensaje sugerido', suggestedMessage: 'Hola, quiero reservar una mesa para dos personas. ¿Qué horarios tienen disponibles?',
  suggestedHint: 'El mensaje se abre rellenado en WhatsApp. Tú decides si lo envías.',
  panelStep: 'Después / en el panel', openPanel: 'Abrir panel de reservas', settingsTitle: 'Ajustes de WhatsApp',
  startStep: 'Inicia la conversación', startHint: 'Pregunta el horario y pide una mesa.',
  confirmStep: 'Comprueba la reserva', confirmHint: 'Comprueba la fecha, la hora y el número de personas en el panel.',
  postVisitPolicy: 'Los comentarios y las encuestas se configuran por separado. Revisa ambos flujos antes de activarlos.',
  verificationCode: 'Código de verificación',
};
export function whatsappCopy(language: string): Copy {
  return language.startsWith('pt') ? pt : language.startsWith('es') ? es : en;
}
